-- Populate legal_content with real content including zero-tolerance language

UPDATE legal_content
SET title = 'Terms and Conditions',
    content = '{"sections": [{"text": "By creating an account or using Merry 360X, you agree to these Terms and Conditions. If you do not agree, do not use the service."}, {"text": "ZERO TOLERANCE POLICY: Merry 360X has a zero-tolerance policy for objectionable content and abusive users. Any content that is harassing, threatening, discriminatory, fraudulent, sexually explicit, or otherwise objectionable is strictly prohibited. Any user found violating this policy will have their content removed immediately and their account permanently terminated."}, {"text": "USER CONDUCT: You agree not to post or share any content that: (a) is defamatory, harassing, or abusive; (b) contains hate speech or promotes discrimination; (c) is fraudulent or misleading; (d) infringes on others rights; (e) contains explicit or violent material; (f) solicits illegal activities."}, {"text": "CONTENT MODERATION: Merry 360X employs automated filtering systems to detect and block prohibited content, including contact information sharing, external links, and abusive language. Our moderation team reviews reported content within 24 hours and takes appropriate action."}, {"text": "REPORTING MECHANISM: Users can report objectionable content or abusive behavior through the in-app report function available on stories, messages, and user profiles. Reports are reviewed by our moderation team, and action is taken within 24 hours."}, {"text": "BLOCKING MECHANISM: Users can block abusive users through the messaging interface. Blocked users cannot send messages or interact with the user who blocked them. All blocking actions are logged, and developers are notified of inappropriate content associated with blocked users."}, {"text": "ENFORCEMENT: Merry 360X reserves the right to remove any content and terminate any user account that violates these terms, at our sole discretion, without prior notice. Violations are investigated within 24 hours of reporting."}, {"text": "CONTACT: For questions about these terms, contact support@merry360x.com."}]}'::jsonb
WHERE content_type = 'terms_and_conditions';

UPDATE legal_content
SET title = 'End User License Agreement',
    content = '{"sections": [{"text": "This End User License Agreement (EULA) governs your use of the Merry 360X mobile application and platform. By creating an account or using the app, you agree to be bound by this EULA."}, {"text": "ZERO TOLERANCE FOR OBJECTIONABLE CONTENT: Merry 360X maintains a strict zero-tolerance policy toward objectionable content. This includes but is not limited to: hate speech, harassment, bullying, threats, discriminatory remarks, sexually explicit material, fraudulent content, and any content that violates applicable laws or regulations. Any such content will be immediately removed upon discovery, and the responsible user will be permanently banned from the platform."}, {"text": "ZERO TOLERANCE FOR ABUSIVE USERS: Abusive behavior, including harassment, intimidation, or targeting of other users, will result in immediate and permanent account termination. Merry 360X is committed to maintaining a safe and respectful community for all users."}, {"text": "CONTENT FILTERING: The app uses automated filters to screen messages and content for prohibited material, including contact details, external links, and abusive language. These filters operate in real-time to prevent objectionable content from being shared."}, {"text": "REPORTING OBJECTIONABLE CONTENT: Users are encouraged to report any content or behavior they believe violates this EULA. Reports can be submitted via the in-app report button available on stories, messages, and user profiles. Our moderation team reviews all reports within 24 hours and takes appropriate action, including content removal and user ejection."}, {"text": "BLOCKING ABUSIVE USERS: Users have the ability to block any other user who is engaging in abusive or unwanted behavior. Once blocked, the abusive user cannot send messages or interact with the user who blocked them. Blocking actions are recorded, and developers are notified of the associated inappropriate content, which is removed from the users feed instantly."}, {"text": "MODERATION AND ENFORCEMENT: Merry 360X will act on all objectionable content reports within 24 hours. Actions may include: removing the offending content, issuing warnings, suspending accounts, or permanently ejecting the user responsible. Repeat offenders will be permanently banned without warning."}, {"text": "CONTACT: For questions or concerns about this EULA, please contact support@merry360x.com."}]}'::jsonb
WHERE content_type = 'eula';
